import { useState } from 'react';
import { useEODList, useEODById } from '../../hooks/useEndOfDay';
import { DataTable } from '../../components/DataTable';
import { PageHeader } from '../../components/PageHeader';
import { formatCurrency } from '../../utils/formatCurrency';
import { formatDate } from '../../utils/formatDate';
import type { EndOfDaySummary } from '../../types/models';

const SummaryRow = ({ summary, onClick }: { summary: EndOfDaySummary; onClick: () => void }) => {
  const topQty = (summary.topProductsByQty as unknown as { productId: number; name: string; qty: number }[]) || [];

  return (
    <div className="bg-white rounded-lg border p-4 cursor-pointer hover:border-blue-300" onClick={onClick}>
      <div className="flex items-center justify-between mb-3">
        <div>
          <p className="font-medium">{formatDate(summary.date, 'long')}</p>
          <p className="text-xs text-gray-400">{summary.totalTransactions} transactions</p>
        </div>
        <div className="text-right">
          <p className="font-bold text-lg">{formatCurrency(summary.totalRevenue)}</p>
          <p className={`text-sm ${summary.totalProfit >= 0 ? 'text-green-600' : 'text-red-600'}`}>
            {formatCurrency(summary.totalProfit)} profit ({summary.profitMarginPercent.toFixed(1)}%)
          </p>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-2 text-xs text-gray-500">
        <div>Cash: {formatCurrency(summary.cashRevenue)}</div>
        <div>Card: {formatCurrency(summary.cardRevenue)}</div>
        <div>Credit: {formatCurrency(summary.creditRevenue + summary.semiCreditRevenue)}</div>
        <div>Generated by: {summary.generatedBy?.fullName || '—'}</div>
      </div>

      {topQty.length > 0 && (
        <div className="mt-2 pt-2 border-t text-xs text-gray-400">
          Top: {topQty.slice(0, 3).map((p) => p.name).join(', ')}
        </div>
      )}
    </div>
  );
};

const DetailView = ({ summary, onBack }: { summary: EndOfDaySummary; onBack: () => void }) => {
  const topQty = (summary.topProductsByQty as unknown as { productId: number; name: string; qty: number }[]) || [];
  const topRev = (summary.topProductsByRevenue as unknown as { productId: number; name: string; revenue: number }[]) || [];

  const revenueData = [
    { method: 'Cash', amount: summary.cashRevenue },
    { method: 'Credit', amount: summary.creditRevenue },
    { method: 'Semi-Credit', amount: summary.semiCreditRevenue },
    { method: 'Card', amount: summary.cardRevenue },
  ].filter((r) => r.amount > 0);

  return (
    <div className="space-y-6">
      <button onClick={onBack} className="text-sm text-blue-600 hover:underline">← Back to list</button>

      <div className="grid grid-cols-4 gap-4">
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Transactions</p>
          <p className="text-2xl font-bold">{summary.totalTransactions}</p>
          <p className="text-xs text-gray-400">{summary.voidedTransactions} voided</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Total Revenue</p>
          <p className="text-2xl font-bold">{formatCurrency(summary.totalRevenue)}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Total Profit</p>
          <p className="text-2xl font-bold">{formatCurrency(summary.totalProfit)}</p>
          <p className="text-xs text-gray-400">{summary.profitMarginPercent.toFixed(1)}% margin</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">New Credit Issued</p>
          <p className="text-2xl font-bold">{formatCurrency(summary.newCreditIssued)}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Opening Cash</p>
          <p className="text-xl font-bold">{formatCurrency(summary.openingCash)}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Cash Sales</p>
          <p className="text-xl font-bold">{formatCurrency(summary.cashSales)}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Change Given</p>
          <p className="text-xl font-bold">{formatCurrency(summary.changeGiven)}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Expected Closing</p>
          <p className="text-xl font-bold">{formatCurrency(summary.expectedClosingCash)}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Actual Closing</p>
          <p className="text-xl font-bold">{formatCurrency(summary.actualClosingCash ?? 0)}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Discrepancy</p>
          <p className={`text-xl font-bold ${summary.cashDiscrepancy && summary.cashDiscrepancy !== 0 ? 'text-red-600' : 'text-green-600'}`}>
            {formatCurrency(summary.cashDiscrepancy ?? 0)}
          </p>
        </div>
      </div>

      {revenueData.length > 0 && (
        <div className="bg-white rounded-lg border">
          <h3 className="text-sm font-medium px-4 py-3 border-b">Revenue by Payment Method</h3>
          <DataTable
            columns={[
              { key: 'method', header: 'Method' },
              { key: 'amount', header: 'Amount', render: (r: { method: string; amount: number }) => formatCurrency(r.amount) },
            ]}
            data={revenueData}
            keyExtractor={(r) => r.method}
          />
        </div>
      )}

      <div className="grid grid-cols-2 gap-6">
        {topQty.length > 0 && (
          <div className="bg-white rounded-lg border">
            <h3 className="text-sm font-medium px-4 py-3 border-b">Top Products by Quantity</h3>
            <DataTable
              columns={[
                { key: 'name', header: 'Product' },
                { key: 'qty', header: 'Qty Sold' },
              ]}
              data={topQty}
              keyExtractor={(p) => p.productId}
            />
          </div>
        )}
        {topRev.length > 0 && (
          <div className="bg-white rounded-lg border">
            <h3 className="text-sm font-medium px-4 py-3 border-b">Top Products by Revenue</h3>
            <DataTable
              columns={[
                { key: 'name', header: 'Product' },
                { key: 'revenue', header: 'Revenue', render: (p: { name: string; revenue: number }) => formatCurrency(p.revenue) },
              ]}
              data={topRev}
              keyExtractor={(p) => p.productId}
            />
          </div>
        )}
      </div>
    </div>
  );
};

export const EODSummaryView = () => {
  const [page, setPage] = useState(1);
  const [selectedId, setSelectedId] = useState<number | null>(null);

  const { data, isLoading } = useEODList({ page, limit: 10 });
  const { data: selectedSummary } = useEODById(selectedId ?? 0);

  if (selectedId && selectedSummary) {
    return (
      <div className="p-6 max-w-5xl">
        <PageHeader title={formatDate(selectedSummary.date, 'long')} subtitle="End of Day Summary" />
        <DetailView summary={selectedSummary} onBack={() => setSelectedId(null)} />
      </div>
    );
  }

  return (
    <div className="p-6 max-w-4xl">
      <PageHeader title="End of Day History" subtitle={data ? `${data.pagination.total} summaries` : ''} />

      {isLoading ? (
        <p className="text-gray-500 text-center py-8">Loading...</p>
      ) : data && data.data && data.data.length > 0 ? (
        <>
          <div className="space-y-3">
            {data.data.map((s) => (
              <SummaryRow key={s.id} summary={s} onClick={() => setSelectedId(s.id)} />
            ))}
          </div>

          {data.pagination.totalPages > 1 && (
            <div className="flex items-center justify-between mt-4 text-sm">
              <p className="text-gray-500">Page {data.pagination.page} of {data.pagination.totalPages}</p>
              <div className="flex gap-2">
                <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} className="px-3 py-1 border rounded disabled:opacity-50">Previous</button>
                <button onClick={() => setPage((p) => p + 1)} disabled={page >= data.pagination.totalPages} className="px-3 py-1 border rounded disabled:opacity-50">Next</button>
              </div>
            </div>
          )}
        </>
      ) : (
        <p className="text-gray-500 text-center py-8">No End of Day summaries found</p>
      )}
    </div>
  );
};
